name: python-unit-test
on: [push]
jobs:
  Run unit tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pytest
        run: sudo apt install python3 python3-pytest 


